name: daily

on:
  workflow_dispatch:
  schedule:
    - cron:  '1 15 * * *'

env:
  TZ: Asia/Seoul

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      
      - name: checkout
        uses: actions/checkout@v3
        with:
            repository: studyqrr12/study
            ref: main
            path: study

      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: studyqrr12/study-daily-mark
          ref: main
          path: study-daily-mark

      - name: Node Start Schedule
        run: |
          cd study-daily-mark
          npm i
          npm start
          cd ..

      - name: Commit files
        run : |
          cd study-daily-mark
          git pull || echo ""
          git add README.md || echo ""
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Github Action Commit" || echo ""
          git push || echo ""
